In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Problem 1: Create Three Different Arrays with Integer Values


# Create array1 with integer values 1, 2, 3
array1 = np.array([1, 2, 3])

# Create array2 with integer values 4, 5, 6
array2 = np.array([4, 5, 6])

# Create array3 with integer values 7, 8, 9
array3 = np.array([7, 8, 9])

In [4]:
array1

array([1, 2, 3])

In [4]:
# Problem 2: Create Two Different Matrices


# Create matrix1
matrix1 = np.array([[1, 2], [3, 4]])

# Create matrix2
matrix2 = np.array([[5, 6], [7, 8]])

In [6]:
print(matrix1)
print(matrix2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [7]:
# Problem 3: Add Matrices


result_addition = matrix1 + matrix2

In [8]:
print(result_addition)

[[ 6  8]
 [10 12]]


In [9]:
# Problem 4: Add and Subtract Vectors with Integer Values

# Create vector1 with integer values
vector1 = np.array([1, 2, 3])

# Create vector2 with integer values
vector2 = np.array([4, 5, 6])

# Perform vector addition
result_addition = vector1 + vector2

# Perform vector subtraction
result_subtraction = vector2 - vector1

In [10]:
print(result_addition)
print(result_subtraction)

[5 7 9]
[3 3 3]


In [11]:
# Problem 5: Multiply Array by Scalar

# Scalar value
scalar = 5

# Array

array_to_multiply = np.array([1, 2, 3])

# Multiply the array by the scalar

result_scalar_multiplication = array_to_multiply * scalar
result_scalar_multiplication

array([ 5, 10, 15])

In [13]:
# Problem 6: Multiply Matrix by Scalar

# Create a 2x2 matrix with integer values
matrix = np.array([[1, 2], [3, 4]])

# Scalar value for multiplication
scalar = 5

# Multiply the matrix by the scalar
result_scalar_multiplication = matrix * scalar
result_scalar_multiplication

array([[ 5, 10],
       [15, 20]])

In [14]:
# Problem 7: Find Determinant of  Matrix 2

# Create matrix1
matrix1 = np.array([[1, 2], [3, 4]])

# Calculate the determinant
determinant_matrix1 = np.linalg.det(matrix1)



matrix2 = np.array([[5, 6], [7, 8]])

determinant_matrix2 = np.linalg.det(matrix2)

In [15]:
print(determinant_matrix2)

-2.000000000000005


In [ ]:
# Problem 8: Find Rank of 3x3 Matrix

# Create matrix3
matrix3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the rank
rank_matrix3 = np.linalg.matrix_rank(matrix3)

In [5]:
# Create matrix3
matrix3 = np.array([[5, 7, 2], [6, 9, 0], [3, 6, 1]])

# Calculate the rank
rank_matrix3 = np.linalg.matrix_rank(matrix3)

In [6]:
print(rank_matrix3)

3


In [7]:
#Example
A = np.array([
        [2, -1, 1, 1],
        [1, 2, -1, -1],
        [-1, 2, 2, 2],
        [1, -1, 2, 1]
    ])
b = np.array([6, 3, 14, 8])

In [9]:
#find the determinant to check if a unique solutions exists
d = np.linalg.det(A)
print(d)

# solution of the system of linear equations with the corresponding coefficients matrix A and free coefficients b
x = np.linalg.solve(A,b)
print(x)

#find the rank of A
rank_a = np.linalg.matrix_rank(A)
print(rank_a)

-16.999999999999993
[2. 3. 4. 1.]
4


In [11]:
# Problem 9: Create the matrix and solution vector for the linear system below. Find the determinant of M, the solution and the linear system and the rank


#4x + 3y + 2z = 25
#-2x + 2y + 3z = -10
#3x -5y + 2z = -4

M = ([
    [4, 3, 2],
    [-2, 2, 3],
    [3, -5, 2]
])

b = np.array([25, -10, -4])
d = np.linalg.det(M)
x = np.linalg.solve(M,b)
r = np.linalg.matrix_rank(M)

print(M)
print(d)
print(x)
print(r)



[[4, 3, 2], [-2, 2, 3], [3, -5, 2]]
122.99999999999994
[ 5.  3. -2.]
3
