# Homework: Intro to pandas

* Defining a Series/DataFrame
* Basic properties of Series/DataFrame
* Indexing and slicing Series/DataFrame

In [1]:
import pandas as pd

### Exercise 1

Create a pandas series that contains 10 elements using 3 different ways.

In [9]:
series_1 = pd.Series([1, 2, 3, 4, 5])
series_2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5})
series_3 = pd.Series([1, 2, 3, 4, 5], index = ['a', 'b', 'c', 'd', 'e'])

print(series_1)
print(series_2)
print(series_3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


### Exercise 2

Create a DataFrame that contains 4 columns and 5 rows using 3 different ways.

In [12]:
df1 = pd.DataFrame({'column1': series_2, 'column2': series_3, 'column3': series_2, 'column4': series_3, 'column5': series_3})
df2 = pd.DataFrame([
    {"column1": 1, "column2": 1, "column3": 1, "column4": 1, 'column5': 1},
    {"column1": 2, "column2": 2, "column3": 2, "column4": 2, 'column5': 2},
    {"column1": 3, "column2": 3, "column3": 3, "column4": 3, 'column5': 3},
    {"column1": 4, "column2": 4, "column3": 4, "column4": 4, 'column5': 4},
    {"column1": 5, "column2": 5, "column3": 5, "column4": 5, 'column5': 5}
])
df3 = pd.DataFrame({
    "column1": [1, 2, 3, 4, 5],
    "column2": [1, 2, 3, 4, 5],
    "column3": [1, 2, 3, 4, 5],
    "column4": [1, 2, 3, 4, 5],
    "column5": [1, 2, 3, 4, 5]
})

print(df1)
print(df2)
print(df3)

   column1  column2  column3  column4  column5
a        1        1        1        1        1
b        2        2        2        2        2
c        3        3        3        3        3
d        4        4        4        4        4
e        5        5        5        5        5
   column1  column2  column3  column4  column5
0        1        1        1        1        1
1        2        2        2        2        2
2        3        3        3        3        3
3        4        4        4        4        4
4        5        5        5        5        5
   column1  column2  column3  column4  column5
0        1        1        1        1        1
1        2        2        2        2        2
2        3        3        3        3        3
3        4        4        4        4        4
4        5        5        5        5        5


### Exercise 3

Given this dataframe

```python
df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 15, 16]
})
```

extract the 3rd element of its index.

In [14]:
df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12],
    'D': [13, 14, 15, 16]
})

print(df['C'])

0     9
1    10
2    11
3    12
Name: C, dtype: int64


### Exercise 4

Using the dataframe from the previous exercise, extract the number of rows and columns.

In [17]:
print(df.shape)

(4, 4)


### Exercise 5

Now extract the values of the dataframe as a numpy array.

In [18]:
print(df.values)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


### Exercise 6

Using the dataframe from the previous exercise, extract the names of the columns.

In [20]:
print(list(df.columns))

['A', 'B', 'C', 'D']


### Exercise 7

Change the name of the columns from `A, B, C, D` to `column_A, column_B, column_C, column_D`.

In [40]:
new_df = df.rename(columns = {'A': 'column_A', 'B': 'column_B', 'C': 'column_C', 'D': 'column_D'})
print(new_df)

   column_A  column_B  column_C  column_D
0         1         5         9        13
1         2         6        10        14
2         3         7        11        15
3         4         8        12        16


### Exercise 8

Using the dataframe from the previous exercise, extract the values of the column `column_B` and store them in a variable.

In [31]:
column_B = new_df['column_B']
print(column_B)

0    5
1    6
2    7
3    8
Name: column_B, dtype: int64


### Exercise 9

Now extract the values of the 3rd row.

In [34]:
print(new_df.iloc[2])

column_A     3
column_B     7
column_C    11
column_D    15
Name: 2, dtype: int64


### Exercise 10

Using the dataframe from the previous exercise, extract the values of the rows 1 and 3, for the columns `column_A` and `column_C`.

Hint: you can use the `loc` method, and using lists of the elements that you want to extract.

In [50]:
print(new_df.loc[[0, 2], 'column_A'])
print(new_df.loc[0:2:2, 'column_C'])

0    1
2    3
Name: column_A, dtype: int64
0     9
2    11
Name: column_C, dtype: int64


### Exercise 11

Using the `:` notation like in lists or ranges, please extract all the rows after the first one.

In [47]:
print(new_df.iloc[1:])

   column_A  column_B  column_C  column_D
1         2         6        10        14
2         3         7        11        15
3         4         8        12        16


### Exercise 12

What is the sum of all the values in `df`?

In [54]:
print(new_df.values.sum())

136
